### ISSUE TITLE
Concepts/Prototypes

### ISSUE THREAD

**Issue by leplerjacob** [waitLess-project/WaitLESS-frontend#8]
Discussion and submission of concepts and prototypes

**Comment by leplerjacob** [comment]
Landing Page idea one

![concept - landingpage](https://user-images.githubusercontent.com/59655536/122968833-f459ad80-d359-11eb-941d-c5e807e67b20.jpg)

**Comment by xchrisbradley** [comment]
Whats the goal of this repo, readme doesnt explain.

For this particular page lets take a step back modularize the structure, I proposed:

layouts: Will house the layout of where the items are store on the page
modules: Will house the actual components themselves

**Comment by leplerjacob** [comment]
Thanks for the feedback @bradleycm . Your approach makes more sense.

We'll need to update the readme for sure. Sorry for the disarray

**Comment by leplerjacob** [comment]
Closing this issue because it is not necessary
